### ISSUE TITLE
Dependency version is incorrect in all packages for sdl2.nuget

### ISSUE THREAD

**Issue by ereOn** [xapdkop/sdl2-nuget#1]
Hi,

The generated package have an incorrect dependency on sdl2.nuget:

They refer to the version of sdl2_tff.nuget instead (2.0.14 at the moment), but sdl2.nuget only exists at 2.0.8 right now.

This makes installation impossible.

See:

https://github.com/xapdkop/sdl2-nuget/blob/7f777e92f190b188b43093b55be795726393bc8a/build/sdl2_ttf.nuget.autopkg#L45

**Comment by xapdkop** [comment]
Hello, Thanks for bugreport. This bug was fixed in [v1.0.1](https://github.com/xapdkop/sdl2-nuget/releases/tag/v1.0.1). Pls wait when update will be available on NuGet.

https://github.com/xapdkop/sdl2-nuget_builder/commit/2e2f5f79fbf7057fd1883ce4b88c40fdbef86a48
